// AUTO-GENERATED by thebridgeflow-front/scripts/generate-video-urls.js — do not edit by hand.
// Source: thebridgeflow-front/scripts/cloudinary-urls.json (produced by upload-to-cloudinary.js).
// Regenerate after any change to that mapping: node thebridgeflow-front/scripts/generate-video-urls.js
//
// Maps the local dev path a video used to be served from (still the shape
// stored in MongoDB formation documents) to its Cloudinary URL, so the app
// can resolve either a legacy local path or a Cloudinary URL to the right
// place to actually play the video from in production.
//
// Deliberately NO /v<timestamp>/ version segment in these URLs — the
// generator strips it even if present in the source JSON. Without a version,
// Cloudinary always serves the current asset for a public_id, so overwriting
// a video in the Cloudinary dashboard (same public_id) shows up on the site
// immediately, with no regeneration needed.
export const VIDEO_URLS = {
  "/stageflow-promo.mp4": "https://drive.google.com/file/d/18hg1ho24_o1d9lFy-_w1AOCAYXpg_TM5/preview",
  "/videos-AI/AI1-enca-month1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/AI1-enca-month1.mp4",
  "/videos-AI/AI1-form-month1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/AI1-form-month1.mp4",
  "/videos-AI/AI2-enca-month1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/AI2-enca-month1.mp4",
  "/videos-AI/AI2-form-month1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/AI2-form-month1.mp4",
  "/videos-AI/AI3-enca-month1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/AI3-enca-month1.mp4",
  "/videos-AI/AI3-form-month1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/AI3-form-month1.mp4",
  "/videos-AI/AI4-enca-month1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/AI4-enca-month1.mp4",
  "/videos-AI/AI4-form-month1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/AI4-form-month1.mp4",
  "/videos-AI/chatbot1-enca-month2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/chatbot1-enca-month2.mp4",
  "/videos-AI/chatbot1-form-month2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/chatbot1-form-month2.mp4",
  "/videos-AI/chatbot2-enca-month2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/chatbot2-enca-month2.mp4",
  "/videos-AI/chatbot2-form-month2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/chatbot2-form-month2.mp4",
  "/videos-AI/chatbot3-enca-month2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/chatbot3-enca-month2.mp4",
  "/videos-AI/chatbot3-form-month2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/chatbot3-form-month2.mp4",
  "/videos-AI/chatbot4-enca-month2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/chatbot4-enca-month2.mp4",
  "/videos-AI/chatbot4-form-month2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-AI/chatbot4-form-month2.mp4",
  "/videos-ANGU-SPRING/back-spring-sem5.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/back-spring-sem5.mp4",
  "/videos-ANGU-SPRING/back-spring-sem6.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/back-spring-sem6.mp4",
  "/videos-ANGU-SPRING/back-spring-sem7.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/back-spring-sem7.mp4",
  "/videos-ANGU-SPRING/back-spring-sem8.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/back-spring-sem8.mp4",
  "/videos-ANGU-SPRING/enca-angu-sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/enca-angu-sem1.mp4",
  "/videos-ANGU-SPRING/enca-angu-sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/enca-angu-sem2.mp4",
  "/videos-ANGU-SPRING/enca-angu-sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/enca-angu-sem3.mp4",
  "/videos-ANGU-SPRING/enca-angu-sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/enca-angu-sem4.mp4",
  "/videos-ANGU-SPRING/enca-back-spring-sem5.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/enca-back-spring-sem5.mp4",
  "/videos-ANGU-SPRING/enca-back-spring-sem6.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/enca-back-spring-sem6.mp4",
  "/videos-ANGU-SPRING/enca-back-spring-sem7.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/enca-back-spring-sem7.mp4",
  "/videos-ANGU-SPRING/enca-back-spring-sem8.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/enca-back-spring-sem8.mp4",
  "/videos-ANGU-SPRING/form-angu-sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/form-angu-sem1.mp4",
  "/videos-ANGU-SPRING/form-angu-sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/form-angu-sem2.mp4",
  "/videos-ANGU-SPRING/form-angu-sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/form-angu-sem3.mp4",
  "/videos-ANGU-SPRING/form-angu-sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-ANGU-SPRING/form-angu-sem4.mp4",
  "/videos-BI/sem1-level1-encad.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem1-level1-encad.mp4",
  "/videos-BI/sem1-level1-form.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem1-level1-form.mp4",
  "/videos-BI/sem2-level1-encad.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem2-level1-encad.mp4",
  "/videos-BI/sem2-level1-form.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem2-level1-form.mp4",
  "/videos-BI/sem3-level1-encad.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem3-level1-encad.mp4",
  "/videos-BI/sem3-level1-form.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem3-level1-form.mp4",
  "/videos-BI/sem4-level1-encad.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem4-level1-encad.mp4",
  "/videos-BI/sem4-level1-form.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem4-level1-form.mp4",
  "/videos-BI/sem5-level2-enca.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem5-level2-enca.mp4",
  "/videos-BI/sem5-level2-form.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem5-level2-form.mp4",
  "/videos-BI/sem6-level2-enca.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem6-level2-enca.mp4",
  "/videos-BI/sem6-level2-form.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem6-level2-form.mp4",
  "/videos-BI/sem7-level2-enca.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem7-level2-enca.mp4",
  "/videos-BI/sem7-level2-form.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem7-level2-form.mp4",
  "/videos-BI/sem8-level2-enca.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem8-level2-enca.mp4",
  "/videos-BI/sem8-level2-form.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-BI/sem8-level2-form.mp4",
  "/videos-CYBER/enca-cyber-sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/enca-cyber-sem1.mp4",
  "/videos-CYBER/enca-cyber-sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/enca-cyber-sem2.mp4",
  "/videos-CYBER/enca-cyber-sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/enca-cyber-sem3.mp4",
  "/videos-CYBER/enca-cyber-sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/enca-cyber-sem4.mp4",
  "/videos-CYBER/enca-cyber-sem5.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/enca-cyber-sem5.mp4",
  "/videos-CYBER/enca-cyber-sem6.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/enca-cyber-sem6.mp4",
  "/videos-CYBER/enca-cyber-sem7.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/enca-cyber-sem7.mp4",
  "/videos-CYBER/enca-cyber-sem8.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/enca-cyber-sem8.mp4",
  "/videos-CYBER/form-cyber-sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/form-cyber-sem1.mp4",
  "/videos-CYBER/form-cyber-sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/form-cyber-sem2.mp4",
  "/videos-CYBER/form-cyber-sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/form-cyber-sem3.mp4",
  "/videos-CYBER/form-cyber-sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/form-cyber-sem4.mp4",
  "/videos-CYBER/form-cyber-sem5.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/form-cyber-sem5.mp4",
  "/videos-CYBER/form-cyber-sem6.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/form-cyber-sem6.mp4",
  "/videos-CYBER/form-cyber-sem7.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/form-cyber-sem7.mp4",
  "/videos-CYBER/form-cyber-sem8.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-CYBER/form-cyber-sem8.mp4",
  "/videos-DEV/enca-dev-sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/enca-dev-sem1.mp4",
  "/videos-DEV/enca-dev-sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/enca-dev-sem2.mp4",
  "/videos-DEV/enca-dev-sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/enca-dev-sem3.mp4",
  "/videos-DEV/enca-dev-sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/enca-dev-sem4.mp4",
  "/videos-DEV/enca-dev-sem5.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/enca-dev-sem5.mp4",
  "/videos-DEV/enca-dev-sem6.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/enca-dev-sem6.mp4",
  "/videos-DEV/enca-dev-sem7.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/enca-dev-sem7.mp4",
  "/videos-DEV/enca-dev-sem8.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/enca-dev-sem8.mp4",
  "/videos-DEV/form-dev-sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/form-dev-sem1.mp4",
  "/videos-DEV/form-dev-sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/form-dev-sem2.mp4",
  "/videos-DEV/form-dev-sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/form-dev-sem3.mp4",
  "/videos-DEV/form-dev-sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/form-dev-sem4.mp4",
  "/videos-DEV/form-dev-sem5.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/form-dev-sem5.mp4",
  "/videos-DEV/form-dev-sem6.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/form-dev-sem6.mp4",
  "/videos-DEV/form-dev-sem7.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/form-dev-sem7.mp4",
  "/videos-DEV/form-dev-sem8.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-DEV/form-dev-sem8.mp4",
  "/videos-feedback/feedback-formation1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation1.mp4",
  "/videos-feedback/feedback-formation10.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation10.mp4",
  "/videos-feedback/feedback-formation2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation2.mp4",
  "/videos-feedback/feedback-formation3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation3.mp4",
  "/videos-feedback/feedback-formation4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation4.mp4",
  "/videos-feedback/feedback-formation5.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation5.mp4",
  "/videos-feedback/feedback-formation6.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation6.mp4",
  "/videos-feedback/feedback-formation7.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation7.mp4",
  "/videos-feedback/feedback-formation8.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation8.mp4",
  "/videos-feedback/feedback-formation9.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-formation9.mp4",
  "/videos-feedback/feedback-pfe1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-pfe1.mp4",
  "/videos-feedback/feedback-pfe2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-pfe2.mp4",
  "/videos-feedback/feedback-pfe3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-pfe3.mp4",
  "/videos-feedback/feedback-pfe4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-pfe4.mp4",
  "/videos-feedback/feedback-pfe5.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-pfe5.mp4",
  "/videos-feedback/feedback-pfe6.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-pfe6.mp4",
  "/videos-feedback/feedback-pfe7.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-pfe7.mp4",
  "/videos-feedback/feedback-pfe8.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/feedback-pfe8.mp4",
  "/videos-feedback/summer-camp1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp1.mp4",
  "/videos-feedback/summer-camp10.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp10.mp4",
  "/videos-feedback/summer-camp2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp2.mp4",
  "/videos-feedback/summer-camp3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp3.mp4",
  "/videos-feedback/summer-camp4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp4.mp4",
  "/videos-feedback/summer-camp5.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp5.mp4",
  "/videos-feedback/summer-camp6.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp6.mp4",
  "/videos-feedback/summer-camp7.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp7.mp4",
  "/videos-feedback/summer-camp8.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp8.mp4",
  "/videos-feedback/summer-camp9.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-feedback/summer-camp9.mp4",
  "/videos-FLUTTER/sem1-enca-flutter-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem1-enca-flutter-backend.mp4",
  "/videos-FLUTTER/sem1-enca-flutter-mob.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem1-enca-flutter-mob.mp4",
  "/videos-FLUTTER/sem1-form-flutter.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem1-form-flutter.mp4",
  "/videos-FLUTTER/sem2-enca-flutter-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem2-enca-flutter-backend.mp4",
  "/videos-FLUTTER/sem2-enca-flutter-mob.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem2-enca-flutter-mob.mp4",
  "/videos-FLUTTER/sem2-form-flutter.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem2-form-flutter.mp4",
  "/videos-FLUTTER/sem3-enca-flutter-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem3-enca-flutter-backend.mp4",
  "/videos-FLUTTER/sem3-enca-flutter-mob.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem3-enca-flutter-mob.mp4",
  "/videos-FLUTTER/sem3-form-flutter.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem3-form-flutter.mp4",
  "/videos-FLUTTER/sem4-enca-flutter-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem4-enca-flutter-backend.mp4",
  "/videos-FLUTTER/sem4-enca-flutter-mob.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem4-enca-flutter-mob.mp4",
  "/videos-FLUTTER/sem4-form-flutter.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-FLUTTER/sem4-form-flutter.mp4",
  "/videos-IoT/enca-frame-sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/enca-frame-sem1.mp4",
  "/videos-IoT/enca-frame-sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/enca-frame-sem2.mp4",
  "/videos-IoT/enca-frame-sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/enca-frame-sem3.mp4",
  "/videos-IoT/enca-frame-sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/enca-frame-sem4.mp4",
  "/videos-IoT/enca-iot-sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/enca-iot-sem1.mp4",
  "/videos-IoT/enca-iot-sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/enca-iot-sem2.mp4",
  "/videos-IoT/enca-iot-sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/enca-iot-sem3.mp4",
  "/videos-IoT/enca-iot-sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/enca-iot-sem4.mp4",
  "/videos-IoT/form-iot-sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/form-iot-sem1.mp4",
  "/videos-IoT/form-iot-sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/form-iot-sem2.mp4",
  "/videos-IoT/form-iot-sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/form-iot-sem3.mp4",
  "/videos-IoT/form-iot-sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-IoT/form-iot-sem4.mp4",
  "/videos-MERN/encad1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/encad1.mp4",
  "/videos-MERN/encad2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/encad2.mp4",
  "/videos-MERN/encad3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/encad3.mp4",
  "/videos-MERN/encad4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/encad4.mp4",
  "/videos-MERN/encad5-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/encad5-backend.mp4",
  "/videos-MERN/encad6-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/encad6-backend.mp4",
  "/videos-MERN/encad7-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/encad7-backend.mp4",
  "/videos-MERN/encad8-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/encad8-backend.mp4",
  "/videos-MERN/sem1.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/sem1.mp4",
  "/videos-MERN/sem2.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/sem2.mp4",
  "/videos-MERN/sem3.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/sem3.mp4",
  "/videos-MERN/sem4.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/sem4.mp4",
  "/videos-MERN/sem5-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/sem5-backend.mp4",
  "/videos-MERN/sem6-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/sem6-backend.mp4",
  "/videos-MERN/sem7-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/sem7-backend.mp4",
  "/videos-MERN/sem8-backend.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/sem8-backend.mp4",
  "/videos-MERN/trailer.mp4": "https://res.cloudinary.com/ychbkjbp/video/upload/stageflow/videos-MERN/trailer.mp4",
};

// formation.videoUrl / trailerVideoUrl fields may already contain a full URL
// (YouTube links, or a Cloudinary URL after the DB migration) — only route
// through the mapping for the old "/videos-..." local-path shape.
export function resolveVideoUrl(localPathOrUrl) {
  if (!localPathOrUrl) return localPathOrUrl;
  // If it's a Google Drive URL, normalize it for iframe preview
  if (isGoogleDriveUrl(localPathOrUrl)) {
    return resolveDriveUrl(localPathOrUrl);
  }
  // Check the VIDEO_URLS mapping first (legacy Cloudinary paths)
  return VIDEO_URLS[localPathOrUrl] || localPathOrUrl;
}

/**
 * Google Drive URL helpers (frontend)
 * These mirror the backend helpers for display purposes.
 */

const DRIVE_FILE_REGEX = /\/file\/d\/([^/?#&]+)/;
const DRIVE_UC_REGEX   = /\/uc\?.*[&?]id=([^&]+)/;
const DRIVE_OPEN_REGEX = /\/open\?.*[&?]id=([^&]+)/;

/**
 * Extracts the Google Drive file ID from various sharing link formats.
 */
export function extractDriveFileId(url = "") {
  for (const regex of [DRIVE_FILE_REGEX, DRIVE_UC_REGEX, DRIVE_OPEN_REGEX]) {
    const m = url.match(regex);
    if (m) return m[1];
  }
  return null;
}

/**
 * Checks if a URL is a Google Drive sharing link.
 */
export function isGoogleDriveUrl(url = "") {
  return url.includes("drive.google.com") && extractDriveFileId(url) !== null;
}

/**
 * Converts a Google Drive sharing link to the appropriate format.
 * For videos: returns a /preview link suitable for <iframe> playback.
 * For images: returns a direct thumbnail URL suitable for <img> tags.
 * For non-Drive URLs: returns the URL unchanged.
 *
 * @param {string} url - The original URL (Drive sharing link or other)
 * @param {"video"|"image"} type - The type of media
 * @returns {string} Normalized URL
 */
export function resolveDriveUrl(url = "", type = "video") {
  const fileId = extractDriveFileId(url);
  if (!fileId) return url; // Not a Drive URL, return as-is

  if (type === "image") {
    return `https://drive.google.com/thumbnail?id=${fileId}&sz=w1000`;
  }

  // Default: video preview URL for iframe
  return `https://drive.google.com/file/d/${fileId}/preview`;
}

/**
 * Vignette d'un fichier Google Drive (image OU vidéo) via notre proxy backend
 * (/api/drive-thumbnail/:fileId), plutôt que le lien direct
 * drive.google.com/thumbnail?id=... — celui-ci répond correctement en
 * navigation directe ou en requête serveur-à-serveur, mais le navigateur
 * refuse de suivre sa redirection (302 → lh3.googleusercontent.com) quand la
 * requête vient d'une <img> intégrée cross-site (restriction anti-hotlinking
 * détectée côté Google via les en-têtes Sec-Fetch-*, vérifié sur le carousel
 * de témoignages : vignette qui reste noire malgré une URL fonctionnelle
 * isolément). Le proxy récupère l'image côté serveur (pas cette restriction
 * pour une requête serveur-à-serveur) et la reesert depuis notre propre
 * origine — voir driveProxy.controller.js.
 * @param {string} url - Lien Google Drive (n'importe quel format supporté)
 * @returns {string|null} URL du proxy, ou null si `url` n'est pas un lien Drive
 */
export function resolveDriveThumbnailProxyUrl(url = "") {
  const fileId = extractDriveFileId(url);
  if (!fileId) return null;
  const apiBase = import.meta.env.VITE_API_URL || "http://localhost:5000/api";
  return `${apiBase}/drive-thumbnail/${fileId}`;
}

/**
 * Auto-detects the type from the URL context and normalizes.
 */
export function autoResolveDriveUrl(url = "") {
  if (!isGoogleDriveUrl(url)) return url;
  const path = url.toLowerCase();
  const isImage = path.includes("image") ||
                  path.match(/\.(jpg|jpeg|png|gif|webp|svg|bmp|ico)/) !== null;
  return resolveDriveUrl(url, isImage ? "image" : "video");
}
